parser: "@typescript-eslint/parser"
plugins:
- "@typescript-eslint"
extends:
- "plugin:@typescript-eslint/recommended"
- "prettier"
- "prettier/@typescript-eslint"
rules:
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/explicit-function-return-type": off

